[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 4;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = csi_clk_byte;
GLOBAL_PRIMARY_0_DRIVERTYPE = MIPIDPHY;
GLOBAL_PRIMARY_0_LOADNUM = 36;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = csi_clk_byte_hs;
GLOBAL_PRIMARY_1_DRIVERTYPE = MIPIDPHY;
GLOBAL_PRIMARY_1_LOADNUM = 225;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = sys_clk_c;
GLOBAL_PRIMARY_2_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_2_LOADNUM = 390;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = u_top_iic/inst_i2c_drive/drive_clk;
GLOBAL_PRIMARY_3_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_3_LOADNUM = 34;
; I/O Bank 0 Usage
BANK_0_USED = 0;
BANK_0_AVAIL = 7;
BANK_0_VCCIO = NA;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 6;
BANK_1_AVAIL = 14;
BANK_1_VCCIO = 1.8V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 14;
BANK_2_AVAIL = 16;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
